### PR TITLE
Explicitly set target linker language for compat CMakeLists.txt

### PR DESCRIPTION
**Pull request by KrzaQ**
This fixes compatibility with CMake's Ninja generator

### CODE REVIEW

**Comment by janisozaur** [comment]
I've submitted https://github.com/backtrace-labs/crashpad/pull/34 as well

**Comment by janisozaur** [comment]
And removed the other commit from #29, it does pass with current CI setup

**Comment by janisozaur** [comment]
any updates?

**Comment by KrzaQ** [comment]
Hi, sorry for the delay! I expect to work on this (and hopefully be done) towards the end of this week.

**Comment by KrzaQ** [comment]
It looks like I finally got the tests working. I'll proceed with this today

**Review by konraddysput — APPROVED** [review]

**Comment by janisozaur** [comment]
It seems you will have to update the `required` jobs' names for this to be merge-able.

**Pull request merged**
