### PR TITLE
Update checkout action to v3

### PR DESCRIPTION
**Pull request by janisozaur**
checkout@v2 is still using Node 12 which is going to be removed in the future:
https://github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12

### CODE REVIEW

**Comment by janisozaur** [comment]
ping

**Comment by BartoszLitwiniuk** [comment]
https://github.com/backtrace-labs/crashpad/pull/59

**Comment by konraddysput** [comment]
It's updated to v3

**Comment by rick-bt** [comment]
And, thank you @janisozaur. :)

**Pull request closed without merging**
